name: sulok
description: A new Flutter project.
publish_to: 'none'


version: 2.2.5+142

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  http: ^1.1.0
  alice: ^0.3.3
  flutter_secure_storage: ^9.2.3
  get: ^4.6.5
  cached_network_image: ^3.3.0
  firebase_messaging: ^15.1.0
  firebase_core: ^3.4.0
  image_picker: ^1.0.2
  fl_chart: ^0.69.2
  flutter_rounded_date_picker: ^3.0.4
  firebase_auth: ^5.2.0
  country_picker: ^2.0.20
  vibration: ^2.0.1
  pin_code_fields: ^8.0.1
  webview_flutter: ^4.2.4
  url_launcher: ^6.1.14
  percent_indicator: ^4.2.3
  geolocator: ^12.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/
     - assets/icons/
     - assets/images/

  fonts:
     - family: IBMPlexSans
       fonts:
         - asset: assets/fonts/IBMPlexSans-Bold.ttf
           weight: 700
         - asset: assets/fonts/IBMPlexSans-Regular.ttf
           weight: 500
         - asset: assets/fonts/IBMPlexSans-Thin.ttf
           weight: 300


